project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
  preview:
    port: 3333

execute:
  freeze: auto # re-render only when source changes

website:
  title: "Data Analytics for Sciences"
  description: "An Introduction to Data Science in Excel and R"
  site-url: "https://ckaoxvii.github.io/CIS-351-Data-Analytics-for-Sciences/"
  
  # announcement:
  #   icon: calendar-check
  #   content: "*Test!*"
  #   type: danger
  #   position: below-navbar

  page-navigation: true

  navbar:
    pinned: true
    background: "#A90533"
    right: 
      - syllabus.qmd
      - schedule.qmd 
      
  sidebar:
      style: 'docked'
      search: false
      background: light
      contents:
        - section: 'Chapter 1: Foundations'
          contents:
            - file: content/section_0102.qmd
            - file: content/section_0103.qmd
            - file: content/section_0104.qmd
        - section: 'Appendices'
          contents:
            - text: "Appendix A"
              file: content/appendix_A.qmd
            - text: "Appendix B"
              file: content/appendix_B.qmd

  page-footer:
    left: Content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by {{< var instructor.name_no_title >}}
    right: Made with <span style='color:#4168b7'>{{< fa brands r-project >}}</span> and [Quarto](https://quarto.org/)

format: 
  html:
    toc: true
    theme:
      - html/custom.scss
    link-external-newwindow: true
    link-external-icon: true 

custom-callout:
  tidydata:
    icon-symbol: 'fa-book'
    color: "#A90533"
  example:
    icon-symbol: "fa-pencil"
    color: "#1B2AFA"
  convention:
    title: "Convention"
    icon-symbol: "fa-warning"
    color: "orange"
  
filters:
- custom-callout